[package]
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
description = "Simple state-based main loop for doing stuff with glium"
license = "Apache-2.0"
name = "stateloop"
repository = "https://github.com/YeyaSwizaw/stateloop"
version = "0.2.0"

[dependencies]
glium = "0.16.0"

[workspace]
members = ["test"]
