[package]
name = "stateloop"
description = "Simple state-based main loop for doing stuff with glium"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
repository = "https://github.com/YeyaSwizaw/stateloop"
documentation = "https://docs.rs/stateloop"
license = "Apache-2.0"

[dependencies]
glium = "*"

[workspace]
members = ["test"]
