[package]
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
description = "Simple state-based main loop for doing stuff with glium"
license = "Apache-2.0"
name = "stateloop"
repository = "https://github.com/YeyaSwizaw/stateloop"
version = "0.2.0"

[dependencies]
vulkano = "0.4.0"
vulkano-win = "0.4.0"
winit = "0.6.4"

[replace]
"vulkano:0.4.0" = { path = "../vulkano/vulkano" }
"vulkano-win:0.4.0" = { path = "../vulkano/vulkano-win" }
"vulkano-shader-derive:0.4.0" = { path = "../vulkano/vulkano-shader-derive" }

[workspace]
members = ["test"]
